version: "3"

services:
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-express-network

  mongo-express:
    container_name: Mongo-Express
    image: mongo-express:latest
    ports:
      - "8081:8081"
    env_file:
      - ./express.env
    links:
      - mongodb
    networks:
      - mongo-express-network

volumes:
  mongodb_data:

networks:
    mongo-express-network:
      driver: bridge