version: "3"
services:
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    env_file:
      ./mongodb.env
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data: